### PR TITLE
Build fixes 01

### PR DESCRIPTION
**Pull request by andrewbird**
Tidy up the repo, add requisite files and add CI to the standalone build.

### CODE REVIEW

**Comment by ecm-pushbx** [comment]
Please change the lmacros import so it *adds* `-I lmacros` without replacing / deleting `-I ../lmacros/` - using both does not hurt.

**Comment by ecm-pushbx** [comment]
You don't need `jn_warn.mac`

**Comment by ecm-pushbx** [comment]
You can give the link to the lmacros repo as https://hg.pushbx.org/ecm/lmacros/rev/323cc150061e to include the specific revision.

**Comment by andrewbird** [comment]
Thanks for the advice, I've updated the commits now.

**Pull request merged**
